ARG UPSTREAM_VERSION

FROM apachesuperset.docker.scarf.sh/apache/superset:${UPSTREAM_VERSION}
COPY --chown=superset superset-frontend/src/assets/images/superset-logo-horiz.png /app/superset/static/assets/images/superset-logo-horiz.png
COPY --chown=superset superset/ /app/superset/

