ARG UPSTREAM_VERSION

FROM apachesuperset.docker.scarf.sh/apache/superset:${UPSTREAM_VERSION}
COPY --chown=superset superset-frontend/src/assets/images/superset-logo-horiz.png /app/superset/static/assets/images/superset-logo-horiz.png
# add css style
COPY --chown=superset superset-frontend/src/assets/css/style.css /app/superset/static/assets/css/style.css
COPY --chown=superset superset/ /app/superset/
RUN pip install newrelic
COPY --chown=superset docker/newrelic.ini /app/superset/newrelic.ini
COPY --chown=superset docker/run-server.sh /usr/bin/run-server.sh
RUN chmod +x /usr/bin/run-server.sh
